name: Dev Firestore rules 2

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  changes:
    name: Changes
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      firestore: ${{ steps.filter.outputs.firestore }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            firestore:
              - 'firestore.*'

  deploy_firestore:
    name: Deploy Firestore
    needs:
      - changes
    if: ${{ needs.changes.outputs.firestore == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 15
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          create_credentials_file: true
          export_environment_variables: true
      - name: Deploy to Firestore
        run: |
          npm install -g firebase-tools
          firebase deploy --only firestore --force --project=dynamic-bounce-dev
